### PR TITLE
nova > vulcan

### PR DESCRIPTION
**Pull request by dominictracey**

### CODE REVIEW

**Review by xavxyz — CHANGES_REQUESTED** [review]
Yay, the future! Thanks 😄 

I believe we should update versions to 1.3.0 also! 👌

**Comment by dominictracey** [comment]
Should we rename the packages to vulcan-social-share, etc. while we are at it?

**Comment by xavxyz** [comment]
Yes please!

**Review by xavxyz — APPROVED** [review]
🚀

**Pull request merged**
